### ISSUE TITLE
Uploading a meshpart does not work

### ISSUE THREAD

**Issue by firsttobebear** [noblox/noblox.js#380]
```javascript
const Noblox = require("noblox.js")
const fs = require("fs") 

const Result = await Noblox.uploadItem("A meshpart", 40, fs.createReadStream("./Meshpart.obj"))
console.log(Result) //Returns 40
```
I am attempting to upload a meshpart using the uploadItem method. Though I do not show it above I do login with my cookie. I looked at the source of the function and it seems to always be uploading as an image. Is uploadItem only supposed to be working with images or can it work with other assettypes?

**Comment by popeeyy** [comment]
Do you have a use case for this? This isn't a bug but rather a feature request as "uploadItem" should actually be called "uploadImage" since it can't upload any other assets. This sounds like a lot more work to implement than its worth as we would have to convert the mesh to Roblox's mesh format version 4.0.1 and then create a part in Roblox's binary format, not just a simple upload of the obj file.
