### ISSUE TITLE
[BUG] CheckDeveloperProductName error when calling updateDeveloperProduct

### ISSUE THREAD

**Issue by 7n7o** [noblox/noblox.js#385]
when caling updateDeveloperProduct i get an error that i am not logged it

**Comment by Neztore** [comment]
Hi there,
I have just tested and the function appears to be working as expected. Your error may be caused by authentication issues, such as not running `setCookie`, or not appropriately waiting for setCookie to complete. See our [Tutorial on authentication](https://noblox.js.org/tutorial-Authentication.html) for more information, and also our tutorial on [Promises](https://noblox.js.org/tutorial-Promises.html).

More support is also available in our Discord.
