### ISSUE TITLE
[BUG] Failed to validate cookie.

### ISSUE THREAD

**Issue by DominicTheD3v** [noblox/noblox.js#831]
When trying to login to any of my Roblox accounts using Noblox.js, I am given the Failed to validate cookie error. I am getting the cookie and running Noblox.js on the same network and even doesn't work on the same PC.

**Comment by Neztore** [comment]
Please see release notes: https://github.com/noblox/noblox.js/releases/tag/v6.0.1

What version of Noblox are you running? You **must** be running at least version 6.0.2 due to a breaking change made by Roblox.

You can check your noblox version by running `npm list noblox.js --depth=0`

**Comment by DominicTheD3v** [comment]
I seem to be running v4.15.1 somehow.

**Comment by DominicTheD3v** [comment]
For some reason NPM hasn't been automatically updating to the newest version. After specifying a version number after Noblox.js everything is working now. Thank you!

**Comment by Neztore** [comment]
It's because its a major version change - by default npm won't upgrade as major indicates a "breaking change" and upgrading could break your code.
Glad it's sorted.
-------- Original Message --------On 08/09/2024 22:31, DominicTheD3v  wrote:
For some reason NPM hasn't been automatically updating to the newest version. After specifying a version number after Noblox.js everything is working now. Thank you!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/noblox/noblox.js/issues/831#issuecomment-2336830675",
"url": "https://github.com/noblox/noblox.js/issues/831#issuecomment-2336830675",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
