### ISSUE TITLE
Move to async/await syntax

### ISSUE THREAD

**Issue by Regalijan** [noblox/noblox.js#853]
It's almost 2025, we are adding methods that use promise constructors and callbacks, and async/await has been supported since *checks notes* February 2017.

Yeah, this is bad.

I have enough to do as it is so I would greatly prefer to not deal with this on my own, hence the help wanted label.

At the very least we should start enforcing this for new methods. We require node 18.18 at the minimum now so there's no legacy support to worry about.

**Comment by BDFL669** [comment]
I'd be happy to assist on this issue as part of my open source contribution

**Comment by Neztore** [comment]
@BDFL669 Please do contribute to the library! We're keen to bring new people on board.
However, I don't think this issue is a good idea.

Yes, async await is nice. It's syntax sugar and it's a lot easier to read for new code. Beyond that, there is no reason to change the code. It won't make it faster, or easier to use from a API consumer perspective and the underlying promises aren't going away.

We have a very limited time budget and I think it's far more important to focus on work that is impactful. Work that fixes bugs or adds new features - not re-factoring for the sake of it. If we use async-await in all new contributions, we'll gradually move over - and I think that is a more sensible, sustainable approach.

If there are any plans to deprecate the classic promise pattern I'd be happy to revisit this but at present its not worth investing time into imo. Happy to discuss further

**Comment by Neztore** [comment]
An example of a more impactful (but similar) change would be re-factoring imports - our import strategy is old and it *does* now cause compatibility issues with newer versions of node.
